### ISSUE TITLE
palanca-studio dependency not found

### ISSUE THREAD

**Issue by jamessnee1** [xesf/agrippa#5]
Hi, I've followed all your readme steps to compile this project, however I'm having an issue with the final step when running 
`yarn add yarn start `
(Yarn gave me a message saying the new command was add instead of install) - output below:

```
yarn add v1.22.22
[1/4] Resolving packages...
error Error: https://registry.yarnpkg.com/palanca-studio: Not found
    at Request.params.callback [as _callback] (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66680:18)
    at Request.self.callback (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141410:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:142382:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:142304:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Thanks so much, keen to try this project!

**Comment by xesf** [comment]
Right, that part of the project was private but the transpiled version was supposed to be includede.

I will have a look at this again and probably just integrate everything together and remove most of its dependencies.

**Comment by lovedayb** [comment]
Hey, did you ever get this working? I'm finding a few weird issues with some of the XMV files that don't convert properly, such as some of the location stills with background music.

I'm trying to convert the whole game into AGS as a side project.

Cheers,
Ben

> Hi, I've followed all your readme steps to compile this project, however I'm having an issue with the final step when running 
> `yarn add yarn start `
> (Yarn gave me a message saying the new command was add instead of install) - output below:
> 
> ```
> yarn add v1.22.22
> [1/4] Resolving packages...
> error Error: https://registry.yarnpkg.com/palanca-studio: Not found
>     at Request.params.callback [as _callback] (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66680:18)
>     at Request.self.callback (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141410:22)
>     at Request.emit (node:events:513:28)
>     at Request.<anonymous> (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:142382:10)
>     at Request.emit (node:events:513:28)
>     at IncomingMessage.<anonymous> (C:\Users\james\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:142304:12)
>     at Object.onceWrapper (node:events:627:28)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1358:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> ```
> 
> Thanks so much, keen to try this project!

**Comment by xesf** [comment]
So the private dependency is in the public folder so I'd say this should work, but the palanca dependency in the package.json needs to be removed to avoid installing the local project and instead use the one in the public folder.

There is no point of having this separate for now, I probably should include all code in here for archiving purposes, or just release the other repo. I will have a look.

**Comment by xesf** [comment]
> Hey, did you ever get this working? I'm finding a few weird issues with some of the XMV files that don't convert properly, such as some of the location stills with background music.

Did you convert them and extracted the video and audio? XMV may have multiple audio tracks and you will need to find which ones to play.

**Comment by lovedayb** [comment]
Yeah I've done most of the extraction but having issues with some of the files such as the location intro cutscenes that use a static background image. For some reason ffmpeg and VLC don't like the video output. 
I'll keep playing around with it.

**Comment by xesf** [comment]
I don't remember but I did had a lot of issues in the past with these.

I've documented all the file formats here, it may help:
https://wiki.scummvm.org/index.php?title=The_X-Files_Game

**Comment by xesf** [comment]
I gave you both @jamessnee1 and @lovedayb access to the private repos if that helps.

**Comment by lovedayb** [comment]
Thanks so much! Will give it a try tonight!
